version: '3'
services:
  pisces-db:
    image: postgres:10.4
    volumes:
      - piscesdbvolume:/var/lib/postgresql/data/
    networks:
      - pisces
  pisces-web:
    build: pisces
    env_file:
      - ./pisces/.env.prod
    volumes:
      - ./pisces:/code
    networks:
      - astraeus-interop
      - pisces
    ports:
      - "8007:8007"
    depends_on:
      - pisces-db
  pisces-cron:
    build:
      context: ./pisces
      dockerfile: Dockerfile.cron
    volumes:
      - /data/logs/cron:/var/log/pisces-cron
    networks:
      - astraeus-interop
      - pisces
  scorpio-db:
    image: postgres:10.4
    volumes:
      - scorpiodbvolume:/var/lib/postgresql/data/
    networks:
      - scorpio
  scorpio-web:
    build: scorpio
    env_file:
      - ./scorpio/.env.prod
    volumes:
      - ./scorpio:/code
    networks:
      - scorpio
      - astraeus-interop
    ports:
      - "8008:8008"
    depends_on:
      - scorpio-db
  scorpio-cron:
    build:
      context: ./scorpio
      dockerfile: Dockerfile.cron
    volumes:
      - /data/logs/cron:/var/log/scorpio-cron
    networks:
      - scorpio
      - astraeus-interop
  argo-db:
    image: postgres:10.4
    volumes:
      - argodbvolume:/var/lib/postgresql/data/
    networks:
      - argo
  argo-web:
    build: argo
    env_file:
      - ./argo/.env.prod
    volumes:
      - ./argo:/code
    networks:
      - argo
      - astraeus-interop
    ports:
      - "8001:8001"
    depends_on:
      - argo-db
  request-broker-db:
    image: postgres:10.4
    volumes:
      - requestbrokerdbvolume:/var/lib/postgresql/data/
    networks:
      - request-broker
  request-broker-web:
    build: request_broker
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./request_broker/.env.prod
    volumes:
      - ./request_broker:/code
    networks:
      - request-broker
      - astraeus-interop
    ports:
      - "8000:8000"
    depends_on:
      - request-broker-db
  dimes-web:
    build: dimes
    env_file:
      - ./dimes/.env.prod
    volumes:
      - ./dimes:/app
      - ./dimes/node_modules:/app/node_modules
    networks:
      - dimes
      - astraeus-interop
    ports:
      - 3000:3000
    stdin_open: true

  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=https://myreadingroom.library.pitt.edu http://myreadingroom.library.pitt.edu http://localhost:3000 https://requestbroker.library.pitt.edu http://requestbroker.library.pitt.edu http://localhost:8000 https://argo.library.pitt.edu http://argo.library.pitt.edu http://localhost:8001 http://localhost:3001 http:localhost:8008 http://localhost:8007
      - http.cors.allow-headers=Content-Type,Access-Control-Allow-Headers,Authorization,X-Requested-With
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - astraeus-interop
    ports:
      - 9200:9200

volumes:
  piscesdbvolume:
  scorpiodbvolume:
  elasticsearch:
  argodbvolume:
  requestbrokerdbvolume:
  dimes:
  nodemodules:

networks:
  scorpio:
  astraeus-interop:
  pisces:
  argo:
  request-broker:
  dimes:
